# Generated by Django 2.2.6 on 2019-11-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
