# Generated by Django 2.2.6 on 2019-11-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191116_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='checkbox',
            field=models.BooleanField(verbose_name='비밀글'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
